<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhci3zv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhci3zv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJhci3zv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJhci3zv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJhci3zv\appDevDebugProjectContainer([
    'container.build_hash' => 'Jhci3zv',
    'container.build_id' => '4bee7ec5',
    'container.build_time' => 1705285995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhci3zv');
