<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZk3iomb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZk3iomb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZk3iomb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZk3iomb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZk3iomb\appDevDebugProjectContainer([
    'container.build_hash' => 'Zk3iomb',
    'container.build_id' => '65efd20c',
    'container.build_time' => 1705246247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZk3iomb');
